# Generated by Django 5.2.1 on 2025-05-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('sito_web', models.URLField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('codice_sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('descrizione_breve', models.TextField()),
                ('descrizione_completa', models.TextField(blank=True, null=True)),
                ('immagine_principale', models.ImageField(upload_to='prodotti/')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_scontato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantita_disponibile', models.PositiveIntegerField(default=0)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso in grammi', max_digits=6, null=True)),
                ('in_evidenza', models.BooleanField(default=False)),
                ('in_vendita', models.BooleanField(default=True)),
                ('nuovo', models.BooleanField(default=False)),
                ('usato', models.BooleanField(default=False)),
                ('condizione', models.CharField(blank=True, help_text='Per prodotti usati, specificare lo stato (Ottimo, Buono, Usato, ecc.)', max_length=50, null=True)),
                ('meta_titolo', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_descrizione', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='prodotti.brand')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='categorie/')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sottocategorie', to='prodotti.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Canna',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prodotti.product')),
                ('tipo_canna', models.CharField(choices=[('SPINNING', 'Spinning'), ('CASTING', 'Casting'), ('SURFCASTING', 'Surfcasting'), ('CARPFISHING', 'Carpfishing'), ('BOLOGNESE', 'Bolognese'), ('INGLESE', 'Inglese'), ('TROTA_LAGO', 'Trota Lago'), ('TROTA_TORRENTE', 'Trota Torrente'), ('FEEDER', 'Feeder'), ('BOMBARDA', 'Bombarda'), ('FISSA', 'Fissa'), ('TRAINA', 'Traina')], max_length=100)),
                ('lunghezza', models.DecimalField(decimal_places=2, help_text='Lunghezza in metri', max_digits=5)),
                ('numero_sezioni', models.PositiveIntegerField(blank=True, null=True)),
                ('potenza_lancio', models.CharField(blank=True, help_text='Es. 10-30g', max_length=50, null=True)),
                ('azione', models.CharField(blank=True, choices=[('ULTRA_LIGHT', 'Ultra Light'), ('LIGHT', 'Light'), ('MEDIUM_LIGHT', 'Medium Light'), ('MEDIUM', 'Medium'), ('MEDIUM_HEAVY', 'Medium Heavy'), ('HEAVY', 'Heavy'), ('EXTRA_HEAVY', 'Extra Heavy')], max_length=50, null=True)),
                ('materiale', models.CharField(blank=True, help_text='Es. Carbonio, Fibra di vetro', max_length=100, null=True)),
                ('ingombro', models.DecimalField(blank=True, decimal_places=2, help_text='Ingombro chiusa in cm', max_digits=5, null=True)),
                ('anelli', models.CharField(blank=True, max_length=100, null=True)),
                ('porta_mulinello', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Canna da pesca',
                'verbose_name_plural': 'Canne da pesca',
            },
            bases=('prodotti.product',),
        ),
        migrations.CreateModel(
            name='Esca',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prodotti.product')),
                ('tipo_esca', models.CharField(choices=[('ARTIFICIALE', 'Artificiale'), ('NATURALE', 'Naturale'), ('VIVA', 'Viva')], max_length=100)),
                ('categoria_artificiale', models.CharField(blank=True, choices=[('HARD_BAIT', 'Hard Bait'), ('SOFT_BAIT', 'Soft Bait'), ('SPOON', 'Spoon'), ('SPINNER', 'Spinner'), ('JIG', 'Jig'), ('POPPER', 'Popper'), ('STICKBAIT', 'Stickbait'), ('CRANKBAIT', 'Crankbait'), ('SWIMBAIT', 'Swimbait'), ('TOPWATER', 'Topwater'), ('ALTRO', 'Altro')], max_length=100, null=True)),
                ('lunghezza_esca', models.DecimalField(blank=True, decimal_places=2, help_text='Lunghezza in cm', max_digits=5, null=True)),
                ('peso_esca', models.DecimalField(blank=True, decimal_places=2, help_text='Peso in grammi', max_digits=5, null=True)),
                ('profondita_lavoro', models.CharField(blank=True, help_text='Es. 0-1m, Superficie', max_length=50, null=True)),
                ('colore', models.CharField(blank=True, max_length=100, null=True)),
                ('galleggiante', models.BooleanField(default=False)),
                ('ancorette', models.PositiveIntegerField(blank=True, help_text='Numero di ancorette', null=True)),
                ('rattlin', models.BooleanField(default=False, help_text='Produce suoni/vibrazioni')),
                ('specie_target', models.CharField(blank=True, help_text='Es. Spigola, Trota, Black Bass', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Esca',
                'verbose_name_plural': 'Esche',
            },
            bases=('prodotti.product',),
        ),
        migrations.CreateModel(
            name='Mulinello',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prodotti.product')),
                ('tipo_mulinello', models.CharField(choices=[('SPINNING', 'Spinning'), ('BAITCASTING', 'Baitcasting'), ('SURFCASTING', 'Surfcasting'), ('CARPFISHING', 'Carpfishing'), ('TRAINA', 'Traina'), ('ELETTRICO', 'Elettrico'), ('FLY', 'Fly')], max_length=100)),
                ('materiale_corpo', models.CharField(blank=True, max_length=100, null=True)),
                ('cuscinetti', models.PositiveIntegerField(blank=True, help_text='Numero di cuscinetti', null=True)),
                ('rapporto_recupero', models.CharField(blank=True, help_text='Es. 6.2:1', max_length=20, null=True)),
                ('peso_mulinello', models.DecimalField(blank=True, decimal_places=2, help_text='Peso in grammi', max_digits=6, null=True)),
                ('capacita_bobina', models.CharField(blank=True, help_text='Es. 0.35mm/150m', max_length=100, null=True)),
                ('freno_massimo', models.DecimalField(blank=True, decimal_places=2, help_text='Potenza freno in kg', max_digits=5, null=True)),
                ('frizione', models.CharField(blank=True, choices=[('ANTERIORE', 'Anteriore'), ('POSTERIORE', 'Posteriore'), ('MAGNETICA', 'Magnetica')], max_length=50, null=True)),
                ('bobina_di_ricambio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mulinello',
                'verbose_name_plural': 'Mulinelli',
            },
            bases=('prodotti.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='prodotti.categoria'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='prodotti/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_principale', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='prodotti.product')),
            ],
            options={
                'verbose_name': 'Immagine prodotto',
                'verbose_name_plural': 'Immagini prodotto',
                'ordering': ['ordine'],
            },
        ),
    ]
